language: node_js
branches:
  only:
    - master
addons:
  firefox: latest
  chrome: stable
before_script:
  - npm run start:mock-server &
  - npm run lint
  - npm run test
script:
  - npm run build
  - npm run test:components
after_script:
  - npm run test:coverage
  - npm run test:coverage:report
after_success:
  - npm run semantic-release
