language: node_js
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master
before_install:
  - npm i -g npm@6
before_script:
  - npm run test
  - npm run lint
script:
- echo "This is the script, but you should probably do something else with it"
